USE CPGSALES;


--- THE PARETO ANALYSIS
-- IN CPG , 20% OF PRODUCTS USUALLY DRIVE 80% OF REVENUE.IDENTIFYING THESE "STAR PRODUCTS" HELPS BUSINESSES PRIORITIZE STOCK.

WITH PRODUCTSALES AS (
     SELECT PRODUCT_NAME,
	 SUM(SALES) AS TOTAL_REVENUE
	 FROM ORDERS
	 GROUP BY PRODUCT_NAME
),
     CUMULATIVESALES AS (
	 SELECT PRODUCT_NAME,
	        TOTAL_REVENUE,
			SUM(TOTAL_REVENUE) OVER (ORDER BY TOTAL_REVENUE DESC) AS RUNNING_TOTAL,
			SUM(TOTAL_REVENUE) OVER() AS GRAND_TOTAL
			FROM PRODUCTSALES
			)

SELECT PRODUCT_NAME,
       TOTAL_REVENUE,
	   (RUNNING_TOTAL/GRAND_TOTAL)*100 AS CUMULATIVE_PERCENTAGE
	   FROM CUMULATIVESALES 
	   WHERE (RUNNING_TOTAL/GRAND_TOTAL) <=0.80
